"""Initial MVP schema

Revision ID: 0a6b3db9f107
Revises: 
Create Date: 2026-04-23 13:34:36.207017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6b3db9f107'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role_default', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('human','ai_agent','contractor')", name='ck_participants_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('project_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('project_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_archived', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('action_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.create_index('idx_action_log_actor', ['actor_id'], unique=False)
        batch_op.create_index('idx_action_log_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_action_log_timestamp', ['timestamp'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('type_id', sa.String(length=36), nullable=False),
    sa.Column('status_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('one_line_summary', sa.Text(), nullable=False),
    sa.Column('estimated_deadline', sa.DateTime(), nullable=True),
    sa.Column('git_repo_url', sa.String(length=500), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('notion_project_id', sa.String(length=100), nullable=True),
    sa.Column('notebooklm_id', sa.String(length=100), nullable=True),
    sa.Column('b24_company_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_touched_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("priority IN ('P0','P1','P2','P3')", name='ck_projects_priority'),
    sa.ForeignKeyConstraint(['status_id'], ['project_statuses.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['project_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_last_touched', ['last_touched_at'], unique=False)
        batch_op.create_index('idx_projects_priority', ['priority'], unique=False)
        batch_op.create_index('idx_projects_status', ['status_id'], unique=False)
        batch_op.create_index('idx_projects_type', ['type_id'], unique=False)

    op.create_table('project_participants',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('role_in_project', sa.String(length=100), nullable=False),
    sa.Column('allocated_weekly_hours', sa.Float(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'participant_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sprint_id', sa.String(length=36), nullable=True),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cpp_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=3), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('notion_page_id', sa.String(length=100), nullable=True),
    sa.Column('git_branch', sa.String(length=200), nullable=True),
    sa.Column('git_pr_url', sa.String(length=500), nullable=True),
    sa.Column('superpowers_spec_path', sa.String(length=500), nullable=True),
    sa.Column('superpowers_plan_path', sa.String(length=500), nullable=True),
    sa.Column('quality_tier', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("priority IN ('P0','P1','P2','P3')", name='ck_tasks_priority'),
    sa.CheckConstraint("quality_tier IS NULL OR quality_tier IN ('T1','T2','T3')", name='ck_tasks_quality_tier'),
    sa.CheckConstraint("status IN ('backlog','todo','in_progress','review','done','blocked','cancelled')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['assignee_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_assignee', ['assignee_id'], unique=False)
        batch_op.create_index('idx_tasks_due', ['due_date'], unique=False)
        batch_op.create_index('idx_tasks_project', ['project_id'], unique=False)
        batch_op.create_index('idx_tasks_sprint', ['sprint_id'], unique=False)
        batch_op.create_index('idx_tasks_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_status')
        batch_op.drop_index('idx_tasks_sprint')
        batch_op.drop_index('idx_tasks_project')
        batch_op.drop_index('idx_tasks_due')
        batch_op.drop_index('idx_tasks_assignee')

    op.drop_table('tasks')
    op.drop_table('project_participants')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_type')
        batch_op.drop_index('idx_projects_status')
        batch_op.drop_index('idx_projects_priority')
        batch_op.drop_index('idx_projects_last_touched')

    op.drop_table('projects')
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.drop_index('idx_action_log_timestamp')
        batch_op.drop_index('idx_action_log_entity')
        batch_op.drop_index('idx_action_log_actor')

    op.drop_table('action_log')
    op.drop_table('project_types')
    op.drop_table('project_statuses')
    op.drop_table('participants')
    # ### end Alembic commands ###
