"""f3b backend_id outbox cursor

Revision ID: 0b8a8a1bb61b
Revises: 52cc9ef055b0
Create Date: 2026-06-14 14:08:32.770525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8a8a1bb61b'
down_revision: Union[str, Sequence[str], None] = '52cc9ef055b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('op', sa.String(length=20), nullable=False),
    sa.Column('entity_kind', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("op IN ('create','update','delete')", name='ck_outbox_op'),
    sa.CheckConstraint("status IN ('pending','sent','failed')", name='ck_outbox_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index('idx_outbox_status', ['status'], unique=False)

    op.create_table('sync_cursors',
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('cursor', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('channel')
    )
    # Только добавляем колонку backend_id (nullable). FK tasks.epic_id -> epics.id
    # намеренно НЕ создаём: миграция Task 2 оставила epic_id колонкой без
    # FK-constraint (batch-режим SQLite), модель просто декларирует связь.
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backend_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('backend_id')

    op.drop_table('sync_cursors')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index('idx_outbox_status')

    op.drop_table('outbox')
    # ### end Alembic commands ###
