"""f3b epic checklist taskmember

Revision ID: 52cc9ef055b0
Revises: e34eb4327643
Create Date: 2026-06-14 14:00:29.610692

Что добавляет:
- epics: эпики/спринты проекта (status, опц. starts_at/ends_at, backend_id),
  индекс idx_epics_project, FK project_id → projects.id.
- checklist_items: чек-лист задачи (is_done/position как Integer 0/1),
  индекс idx_checklist_task, FK task_id → tasks.id (ondelete CASCADE).
- task_members: участники задачи с ролью (составной PK task_id+participant_id+
  role), CHECK ck_task_members_role IN ('responsible','executor','watcher').
- tasks.epic_id (TEXT NULL).

Нюанс SQLite/batch: FK tasks.epic_id → epics.id НЕ создаётся как constraint.
В batch-режиме (пересоздание таблицы) безымянный FK падает с
"Constraint must have a name", а именованный inline-FK на `epics` создаёт
циклическую зависимость DDL (epics ссылается на projects, tasks — на epics,
checklist/task_members — на tasks). FK не критичен для SQLite-приложения
(целостность держится в коде/ORM), поэтому добавляем только колонку. На
уровне ORM (`Task.epic_id`) ForeignKey оставлен для метаданных/документации.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '52cc9ef055b0'
down_revision: Union[str, Sequence[str], None] = 'e34eb4327643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('backend_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('epics', schema=None) as batch_op:
        batch_op.create_index('idx_epics_project', ['project_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_done', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('backend_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index('idx_checklist_task', ['task_id'], unique=False)

    op.create_table('task_members',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('responsible','executor','watcher')", name='ck_task_members_role'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'participant_id', 'role')
    )
    # tasks.epic_id — только колонка, без FK-constraint (см. docstring).
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epic_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('epic_id')

    op.drop_table('task_members')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index('idx_checklist_task')

    op.drop_table('checklist_items')
    with op.batch_alter_table('epics', schema=None) as batch_op:
        batch_op.drop_index('idx_epics_project')

    op.drop_table('epics')
    # ### end Alembic commands ###
