"""f3b sync_policy counterparty

Revision ID: e34eb4327643
Revises: ca84c1d9b54e
Create Date: 2026-06-14 13:48:14.545598

Что добавляет:
- sync_policies: справочник политик синка (local/epics/media/full).
- counterparties: контрагенты (kind person/company) с CHECK ck_counterparties_kind.
- project_types.default_sync_policy (FK → sync_policies.slug, nullable).
- projects.owner_id / customer_id (FK → counterparties.id, nullable).
- projects.sync_policy (FK → sync_policies.slug, nullable).
- projects.backend_id (TEXT NULL).
- Seed: 4 политики синка; default_sync_policy типам (client→full, dev→epics,
  test/inbox→local); контрагенты НЕ сидятся здесь (generic — см. seeds.py);
  best-effort owner проектам по owner-тегу.
"""
from __future__ import annotations

from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e34eb4327643'
down_revision: Union[str, Sequence[str], None] = 'ca84c1d9b54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('git_namespace', sa.String(length=200), nullable=True),
    sa.Column('backend_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('person','company')", name='ck_counterparties_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sync_policies',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sync_epic', sa.Integer(), nullable=False),
    sa.Column('sync_task', sa.Integer(), nullable=False),
    sa.Column('sync_checklist', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    with op.batch_alter_table('project_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_sync_policy', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(
            'fk_project_types_default_sync_policy', 'sync_policies',
            ['default_sync_policy'], ['slug'],
        )

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('sync_policy', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('backend_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            'fk_projects_sync_policy', 'sync_policies', ['sync_policy'], ['slug'],
        )
        batch_op.create_foreign_key(
            'fk_projects_owner_id', 'counterparties', ['owner_id'], ['id'],
        )
        batch_op.create_foreign_key(
            'fk_projects_customer_id', 'counterparties', ['customer_id'], ['id'],
        )

    # ### end Alembic commands ###

    # --- seed: sync policies + default_sync_policy типам -------------------
    sync_policies_tbl = sa.table(
        "sync_policies",
        sa.column("slug", sa.String),
        sa.column("name", sa.String),
        sa.column("sync_epic", sa.Integer),
        sa.column("sync_task", sa.Integer),
        sa.column("sync_checklist", sa.Integer),
        sa.column("created_at", sa.DateTime),
    )
    now = datetime.utcnow()
    op.bulk_insert(sync_policies_tbl, [
        {"slug": "local", "name": "Локально (ничего наружу)", "sync_epic": 0, "sync_task": 0, "sync_checklist": 0, "created_at": now},
        {"slug": "epics", "name": "Только эпики (вехи)", "sync_epic": 1, "sync_task": 0, "sync_checklist": 0, "created_at": now},
        {"slug": "media", "name": "Эпики + задачи", "sync_epic": 1, "sync_task": 1, "sync_checklist": 0, "created_at": now},
        {"slug": "full", "name": "Полностью", "sync_epic": 1, "sync_task": 1, "sync_checklist": 1, "created_at": now},
    ])
    # дефолтная политика типам: dev → epics, client-project → full
    op.execute(sa.text("UPDATE project_types SET default_sync_policy='full' WHERE slug='client-project'"))
    op.execute(sa.text(
        "UPDATE project_types SET default_sync_policy='epics' "
        "WHERE slug IN ('business-product','personal-utility','personal-project','shared-infrastructure')"
    ))
    op.execute(sa.text("UPDATE project_types SET default_sync_policy='local' WHERE slug IN ('test','inbox')"))
    # --- контрагенты НЕ сидятся в миграции (раньше тут были личные company/person).
    # Базовые контрагенты теперь в seeds.py (generic, без реальных имён); владелец
    # проекта проставляется командами при создании. Backfill owner_id по owner-тегам
    # убран как user-specific — на свежей БД он no-op (нет таких данных).


def downgrade() -> None:
    """Downgrade schema."""
    # --- удаляем seed-строки ----------------------------------------------
    # (контрагенты в этой миграции больше не сидятся — нечего удалять)
    op.execute(sa.text("DELETE FROM sync_policies WHERE slug IN ('local','epics','media','full')"))

    # ### commands auto generated by Alembic - please adjust! ###
    # batch drop_column в SQLite пересоздаёт таблицу без колонок и их FK,
    # поэтому отдельный drop_constraint для безымянных FK не нужен (и упал бы).
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('backend_id')
        batch_op.drop_column('sync_policy')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('project_types', schema=None) as batch_op:
        batch_op.drop_column('default_sync_policy')

    op.drop_table('sync_policies')
    op.drop_table('counterparties')
    # ### end Alembic commands ###
